apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: inventario-seguro
type: Opaque
stringData:
  LDAP_BIND_USER: "ITU\\Administrador"
  LDAP_BIND_PASSWORD: "Itu12345!"
  SQL_SERVER_USER: "ITU\\Administrador"
  SQL_SERVER_PASSWORD: "Itu12345!"
  SECRET_KEY: "super-secret-key-egi"
  MONGO_USER: "admin"
  MONGO_PASSWORD: "Itu2026*"
