apiVersion: v1
kind: Secret
metadata:
  name: sql-secret
  namespace: inventario-seguro
type: Opaque
data:
  SA_PASSWORD: TXlTdHJvbmdQYXNzMTIzIQ==
  DB_NAME: dWJpY2FjaW9uX2Ri

---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: inventario-seguro
type: Opaque
data:
  MONGO_ROOT_USER: cm9vdA==
  MONGO_ROOT_PASSWORD: TW9uZ29QYXNzMTIz

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: inventario-seguro
type: Opaque
data:
  SECRET_KEY: c3VwZXItc2VjcmV0LWtleS1lZ2k=